const teams = [
    {
        id: 1,
        teamName: 'Manchester City',
        stadiumName: 'Ethihad Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg',
        website: 'https://www.mancity.com/',
      }, 
      {
      id: 2,
      teamName: 'Liverpool FC',
      stadiumName: 'Anfield',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png',
      website: 'https://www.liverpoolfc.com/',
    },
    {
      id: 3,
      teamName: 'Manchester United',
      stadiumName: 'Old Trafford',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/640px-Manchester_United_FC_crest.svg.png',
      website: 'https://www.manutd.com/',
    },
    {
        id: 4,
        teamName: 'Arsenal FC',
        stadiumName: 'Emirates Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png',
        website: 'https://www.arsenal.com/',
      },
      {
        id: 5,
        teamName: 'Tottenham Hotspur',
        stadiumName: 'Tottenham Hotspur Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/800px-Tottenham_Hotspur.svg.png',
        website: 'https://www.tottenhamhotspur.com/',
      },
      {
        id: 6,
        teamName: 'Chelsea FC',
        stadiumName: 'Stamford Bridge',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/800px-Chelsea_FC.svg.png',
        website: 'https://www.chelseafc.com/en',
      },
      {
        id: 7,
        teamName: 'Aston Villa',
        stadiumName: 'Villa Park',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Aston_Villa_FC_new_crest.svg/1200px-Aston_Villa_FC_new_crest.svg.png',
        website: 'https://www.avfc.co.uk/',
      },
      {
        id: 8,
        teamName: 'Newcastle United FC',
        stadiumName: "St. James' Park",
        logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuPA3mtCSNoxf0glrO0olGDpkEtGg3CoUBXA&s',
        website: 'https://www.newcastleunited.com/en',
      },
      {
        id: 9,
        teamName: 'Brighton & Hove Albion',
        stadiumName: 'American Express Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/d/d0/Brighton_and_Hove_Albion_FC_crest.svg',
        website: 'https://www.brightonandhovealbion.com/',
      },
      {
        id: 10,
        teamName: 'Nottingham Forest',
        stadiumName: 'City Ground',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Nottingham_Forest_F.C._logo.svg/1200px-Nottingham_Forest_F.C._logo.svg.png',
        website: 'https://www.nottinghamforest.co.uk/',
      },
      {
        id: 11,
        teamName: 'Fulham FC',
        stadiumName: 'Craven Cottage',
        logo: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg',
        website: 'https://www.fulhamfc.com/',
      },
      {
        id: 12,
        teamName: 'Brentford FC',
        stadiumName: 'Gtech Community Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/1200px-Brentford_FC_crest.svg.png',
        website: 'https://www.brentfordfc.com/en',
      },
      {
        id: 13,
        teamName: 'AFC Bournmouth',
        stadiumName: 'Vitality Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/640px-AFC_Bournemouth_%282013%29.svg.png',
        website: 'https://www.afcb.co.uk/',
      },
      {
        id: 14,
        teamName: 'West Ham FC',
        stadiumName: 'London Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/1200px-West_Ham_United_FC_logo.svg.png',
        website: 'https://www.whufc.com/',
      },
      {
        id: 15,
        teamName: 'Leicster City',
        stadiumName: 'King Power Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/800px-Leicester_City_crest.svg.png',
        website: 'https://www.lcfc.com/?lang=en',
      },
      {
        id: 16,
        teamName: 'Crystal Palace',
        stadiumName: 'Selhurst Park Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo_%282022%29.svg/1200px-Crystal_Palace_FC_logo_%282022%29.svg.png',
        website: 'https://www.cpfc.co.uk/',
      },
      {
        id: 17,
        teamName: 'Ipswich Town',
        stadiumName: 'Portman Road Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/4/43/Ipswich_Town.svg',
        website: 'https://www.itfc.co.uk/',
      },
      {
        id: 18,
        teamName: 'Southampton FC',
        stadiumName: "St Mary's Stadium",
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/FC_Southampton.svg/1200px-FC_Southampton.svg.png',
        website: 'https://www.southamptonfc.com/en',
      },
      {
        id: 19,
        teamName: 'Everton FC',
        stadiumName: 'Everton Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg',
        website: 'https://www.evertonfc.com/',
      },
      {
        id: 20,
        teamName: 'Wolverhampton Wanderers FC',
        stadiumName: 'Molineux Stadium',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Wolverhampton_Wanderers_FC_crest.svg/1200px-Wolverhampton_Wanderers_FC_crest.svg.png',
        website: 'https://www.wolves.co.uk/',
      },
  ];
  
  export default teams;